name: Run Cypress Tests - Production

on: [push]

jobs:
  cypress:
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: https://dish-swap.pages.dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_baseUrl: ${{ env.CYPRESS_BASE_URL }}
